// <auto-generated />
namespace CourseOne.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_descriptio_to_TableCourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_descriptio_to_TableCourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202004160946245_add_descriptio_to_TableCourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
